Repository Code-the-Change-YYC/YW-NLP-Report-Classifier, pull requests merged in 2021-03, with the labels that each got.

#76 [NLP-72] Refactor all Python docstrings
  app.py
  models/model.py
  models/svm_model.py
  preprocess/clean/lowercaser.py
  preprocess/clean/word_character_filter.py
  preprocess/datetime_map/mapper.py
  preprocess/incident_types/column_merge.py
  preprocess/incident_types/mapper.py
  preprocess/lemmatize/ntlk_lemmatize.py
  preprocess/preprocessor.py
  preprocess/report_data.py
  preprocess/scrubadub_scrubber/description_scrub.py
  preprocess/spacy_scrubber/description_scrub.py
  server/interceptum_adapter.py
  server/risk_scores/risk_scores.py
  training/description_classification/utils.py
Labels: NLP-72

#77 [NLP-149] Add time of critical incident to risk assessment
  server/risk_scores/risk_assessment.py
  server/risk_scores/risk_scores.py
Labels: NLP-149

#78 [NLP-146] Fix autocomplete toggle
  client/src/App.js
  client/src/components/DateInput.js
  client/src/components/IncTypePrimaryField.js
  client/src/components/SelectInput.js
  client/src/components/TextInput.js
  client/src/hooks/useAutocomplete.js
  client/src/hooks/useDateFieldInfo.js
  client/src/hooks/useIncTypeOptions.js
  client/src/hooks/useSelectFieldInfo.js
  client/src/hooks/useTextFieldInfo.js
Labels: NLP-146

#81 [NLP-150] [NLP-151] [NLP-158] Add autocomplete to child involved and guest involved
  client/src/App.js
  client/src/components/DateInput.js
  client/src/components/SelectInput.js
  client/src/components/TextInput.js
  client/src/hooks/useAutocomplete.js
  client/src/hooks/useFormOptions.js
  client/src/hooks/useSubmit.js
  cms/cirForm.json
  cms/schemas/cirForm.js
Labels: NLP-150, NLP-151, NLP-158

#84 [NLP-159] Show loading text after pressing submit
  client/src/App.css
  client/src/components/ModalBox.js
  client/src/hooks/useSubmit.js
Labels: NLP-159
